# Generated by Django 5.0.8 on 2024-08-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysed_text', models.CharField(max_length=400)),
                ('analysis_result', models.IntegerField(default=0)),
            ],
        ),
    ]
